name: mobile_scanner
description: A universal barcode and QR code scanner for Flutter based on MLKit. Uses CameraX on Android, AVFoundation on iOS and Apple Vision & AVFoundation on macOS.
version: 4.0.1
repository: https://github.com/juliansteenbakker/mobile_scanner

screenshots:
- description: 'Flutter Demo Home Page'
  path: example/screenshots/homepage.png
- description: 'Mobile Scanner with controller'
  path: example/screenshots/controller.png
- description: 'Mobile Scanner with controller (returning image)'
  path: example/screenshots/returningImage.png
- description: 'Mobile Scanner with zoom slider'
  path: example/screenshots/zoomSlider.png
- description: 'Mobile Scanner with overlay'
  path: example/screenshots/overlay.png

environment:
  sdk: ">=3.1.0 <4.0.0"
  flutter: ">=3.13.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_web_plugins:
    sdk: flutter
  js: ">=0.6.3 <0.8.0"

dev_dependencies:
  flutter_test:
    sdk: flutter
  lint: ">=1.10.0 <3.0.0"

flutter:
  plugin:
    platforms:
      android:
        package: dev.steenbakker.mobile_scanner
        pluginClass: MobileScannerPlugin
      ios:
        pluginClass: MobileScannerPlugin
      macos:
        pluginClass: MobileScannerPlugin
      web:
        pluginClass: MobileScannerWebPlugin
        fileName: mobile_scanner_web_plugin.dart
